"""
LLM Fallback MLP Trainer — EZKL-provable deterministic safety net.

Trains a small MLP that mirrors the DeterministicFallbackModel's rule-based
logic, so that the fallback decision can be proven via EZKL.

Architecture: MLP (Linear + ReLU only — EZKL-compatible)
Input:  10 features from DeterministicFallbackModel.to_feature_vector()
Output: 3 logits (execute, reject, defer_to_human)

Training data: generated by running the rule-based model on synthetic scenarios.
"""
from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn as nn

logger = logging.getLogger(__name__)

MODEL_DIR = Path(__file__).resolve().parents[2] / "data" / "ezkl_models" / "llm_fallback"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

DECISIONS = ["execute", "reject", "defer_to_human"]
DECISION_TO_IDX = {d: i for i, d in enumerate(DECISIONS)}

FEATURE_NAMES = [
    "risk_score",
    "anomaly_score",
    "correlation",
    "il_bps",
    "slippage_bps",
    "health_factor",
    "price_deviation_bps",
    "optimality_gap_bps",
    "value_eth",
    "skill_type",
]


class FallbackMLP(nn.Module):
    """
    Small MLP for 3-class fallback decision — EZKL-compatible.

    Input:  10 features (normalised)
    Output: 3-class logits (execute, reject, defer_to_human)
    """

    def __init__(self, n_features: int = 10, n_classes: int = 3) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_features, 32),
            nn.ReLU(),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Linear(16, n_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


def export_onnx(
    model: FallbackMLP,
    path: str,
    n_features: int = 10,
    opset_version: int = 13,
) -> None:
    """Export fallback MLP to ONNX for EZKL."""
    model.eval()
    dummy = torch.randn(1, n_features)
    torch.onnx.export(
        model,
        dummy,
        path,
        input_names=["features"],
        output_names=["logits"],
        dynamic_axes=None,
        opset_version=opset_version,
        dynamo=False,
    )


def _generate_training_data(n_samples: int = 2000) -> tuple[np.ndarray, np.ndarray]:
    """
    Generate training data by running the rule-based DeterministicFallbackModel
    on synthetic scenarios. The MLP learns to replicate the rule-based logic.
    """
    from app.ml.llm_fallback.fallback_model import DeterministicFallbackModel

    rule_model = DeterministicFallbackModel()
    rng = np.random.default_rng(42)

    SKILL_NAMES = [
        "zk_risk_score", "zk_anomaly_detection", "zk_correlation_risk",
        "zk_il_predictor", "zk_yield_optimality", "zk_slippage_bound",
        "zk_liquidation_risk", "zk_mev_resistance", "risk_assessment",
        "pool_safety",
    ]

    X_list = []
    y_list = []

    for _ in range(n_samples):
        skill = rng.choice(SKILL_NAMES)

        # Generate random skill inputs
        inputs: dict[str, Any] = {
            "risk_score": int(rng.uniform(0, 50)),
            "anomaly_score": int(rng.uniform(0, 80)),
            "correlation": int(rng.uniform(0, 100)),
            "il_bps": int(rng.uniform(0, 800)),
            "slippage_bps": int(rng.uniform(0, 100)),
            "health_factor": float(rng.uniform(0.5, 3.0)),
            "price_deviation_bps": int(rng.uniform(0, 100)),
            "optimality_gap_bps": int(rng.uniform(0, 500)),
            "value_eth": float(rng.uniform(0.01, 50.0)),
        }

        # Get rule-based decision as ground truth
        decision = rule_model.predict(skill, inputs)
        label = DECISION_TO_IDX[decision.decision]

        # Extract feature vector
        features = rule_model.to_feature_vector(skill, inputs)
        X_list.append(features)
        y_list.append(label)

    return np.array(X_list, dtype=np.float32), np.array(y_list, dtype=np.int64)


async def train_fallback_model(
    n_samples: int = 2000,
    epochs: int = 500,
    lr: float = 1e-3,
) -> dict[str, Any]:
    """
    Train the LLM fallback MLP and export to ONNX.

    The model replicates the rule-based DeterministicFallbackModel,
    making it provable via EZKL.

    Returns:
        Dict with model_path, onnx_path, model_hash, accuracy, etc.
    """
    logger.info("Training LLM fallback MLP...")

    X, y = _generate_training_data(n_samples)

    # Normalise features
    X_min = X.min(axis=0)
    X_max = X.max(axis=0)
    X_range = np.where(X_max - X_min > 1e-8, X_max - X_min, 1.0)
    X_normed = (X - X_min) / X_range

    norm_params = {"min": X_min.tolist(), "range": X_range.tolist()}
    (MODEL_DIR / "norm_params.json").write_text(json.dumps(norm_params))

    # Train MLP
    model = FallbackMLP(n_features=len(FEATURE_NAMES), n_classes=len(DECISIONS))
    X_tensor = torch.tensor(X_normed, dtype=torch.float32)
    y_tensor = torch.tensor(y, dtype=torch.long)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)
    criterion = nn.CrossEntropyLoss()

    model.train()
    for epoch in range(epochs):
        optimizer.zero_grad()
        logits = model(X_tensor)
        loss = criterion(logits, y_tensor)
        loss.backward()
        optimizer.step()

    model.eval()
    final_loss = loss.item()

    # Accuracy
    with torch.no_grad():
        preds = model(X_tensor).argmax(dim=1).numpy()
    accuracy = float((preds == y).mean())

    class_dist = {DECISIONS[i]: int((y == i).sum()) for i in range(len(DECISIONS))}
    logger.info(
        "Fallback MLP trained: %d epochs, loss=%.4f, accuracy=%.3f, dist=%s",
        epochs, final_loss, accuracy, class_dist,
    )

    # Save weights
    weights_path = MODEL_DIR / "llm_fallback_mlp.pt"
    torch.save(model.state_dict(), str(weights_path))

    # Export ONNX
    onnx_path = MODEL_DIR / "llm_fallback.onnx"
    export_onnx(model, str(onnx_path), n_features=len(FEATURE_NAMES))
    logger.info("Fallback ONNX exported to %s", onnx_path)

    # Model hash
    model_hash = hashlib.sha256(onnx_path.read_bytes()).hexdigest()

    # Calibration data for EZKL
    cal_data = X_normed[:5].tolist()
    (MODEL_DIR / "calibration.json").write_text(json.dumps({"input_data": cal_data}))

    # Save metadata
    meta = {
        "model_hash": model_hash,
        "onnx_path": str(onnx_path),
        "weights_path": str(weights_path),
        "norm_params_path": str(MODEL_DIR / "norm_params.json"),
        "training_samples": len(X),
        "epochs": epochs,
        "final_loss": final_loss,
        "accuracy": accuracy,
        "class_distribution": class_dist,
        "feature_names": FEATURE_NAMES,
        "decisions": DECISIONS,
        "architecture": "10→32→16→3",
        "trained_at": datetime.utcnow().isoformat(),
    }
    (MODEL_DIR / "training_metadata.json").write_text(json.dumps(meta, indent=2))

    return {
        "status": "success",
        "model_hash": model_hash,
        "onnx_path": str(onnx_path),
        "training_samples": len(X),
        "accuracy": accuracy,
        "class_distribution": class_dist,
    }


async def setup_fallback_ezkl(force: bool = False) -> dict[str, Any]:
    """
    Run EZKL setup for the LLM fallback model.

    Requires: train_fallback_model() must have been run first.
    """
    from app.services.ezkl_prover_service import get_ezkl_prover

    meta_path = MODEL_DIR / "training_metadata.json"
    if not meta_path.exists():
        return {"status": "error", "message": "No trained model. Run train_fallback_model() first."}

    meta = json.loads(meta_path.read_text())
    onnx_path = meta.get("onnx_path")
    if not onnx_path or not Path(onnx_path).exists():
        return {"status": "error", "message": f"ONNX not found at {onnx_path}"}

    # Load calibration data
    cal_path = MODEL_DIR / "calibration.json"
    cal_data = None
    if cal_path.exists():
        cal_data = json.loads(cal_path.read_text()).get("input_data")

    prover = get_ezkl_prover()
    artifacts = await prover.setup_model(
        model_name="llm_fallback",
        onnx_path=onnx_path,
        calibration_data=cal_data,
        input_scale=7,
        param_scale=7,
        bits=16,
        logrows=17,
        force=force,
    )

    return {
        "status": "success",
        "model_name": "llm_fallback",
        "model_hash": artifacts.model_hash,
        "compiled": str(artifacts.compiled_model_path),
        "pk": str(artifacts.pk_path),
        "vk": str(artifacts.vk_path),
        "ready": artifacts.is_ready(),
    }
