# Source Generated with Decompyle++
# File: vault_allocation_executor.cpython-312.pyc (Python 3.12)

'''
Vault Allocation Executor — Phase C

Takes an AllocationDecision (from ai_allocation.py) and:
1. Parses pool_ids → token0 / token1 addresses
2. Converts USD amounts → token-wei amounts using static price table
3. Calls ekubo_lp_service.build_lp_add() for each pool allocation
4. Optionally submits on-chain when EXECUTOR_LIVE_SUBMIT=true
5. Records execution results in the SQLite ledger (pending → active / failed)
6. Returns structured ExecutionResult per allocation

No mocks.  Depends on:
  - ekubo_execution_service.build_lp_add_calldata (tick auto-estimation)
  - contract_executor.ContractExecutor (starkli invoke)
  - real_pool_aggregator._TOKEN_META (price / decimals)
  - ledger_service.LedgerService (audit trail)
'''
from __future__ import annotations
import logging
import os
import uuid
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from typing import Any
from app.services.ai_allocation import AllocationDecision, PoolAllocation
from app.services.real_pool_aggregator import _TOKEN_META, _TOKEN_SYMBOLS
logger = logging.getLogger(__name__)
_DEFAULT_FEE_TIER = 3000
_CHAIN_ID = os.getenv('EKUBO_CHAIN_ID', '0x534e5f5345504f4c4941')
_VAULT_WALLET = os.getenv('VAULT_WALLET_ADDRESS', '0x05fe812551bec726f1bf5026d5fb88f06ed411a753fb4468f9e19ebf8ced1b3d')
LPExecutionResult = <NODE:12>()
ExecutionBatch = <NODE:12>()
_SYMBOL_TO_ADDRESS: 'dict[str, str]' = { }
for _addr, _sym in _TOKEN_SYMBOLS.items():
    if not _sym not in _SYMBOL_TO_ADDRESS and len(_addr) > len(_SYMBOL_TO_ADDRESS.get(_sym, '')):
        continue
    _SYMBOL_TO_ADDRESS[_sym] = _addr

def _parse_pool_id(pool_id = None):
    '''
    Parse pool_id generated by real_pool_aggregator._pool_id().
    Format: ekubo:{token0_addr}:{token1_addr}:{fee}:{idx}
    Returns (token0, token1, fee_tier).
    '''
    parts = pool_id.split(':')
    if len(parts) >= 4 and parts[0] == 'ekubo':
        token0_raw = parts[1]
        token1_raw = parts[2]
        fee_raw = parts[3]
        fee_tier = int(float(fee_raw) * 1000000) if '.' in fee_raw else int(fee_raw)
        return (token0_raw, token1_raw, fee_tier)
    return (None, '', _DEFAULT_FEE_TIER)
# WARNING: Decompyle incomplete


def _resolve_token_address(raw = None):
    '''If raw is already a hex address, return it. Otherwise try symbol lookup.'''
    if raw.startswith('0x') and len(raw) > 6:
        return raw
    if None == '0x0' or raw == '0x00':
        return _SYMBOL_TO_ADDRESS.get('ETH', raw)
    return None.get(raw.upper(), raw)


def _symbol_for_address(addr = None):
    '''Resolve address → symbol for price/decimal lookup.'''
    norm = addr.strip().lower()
    for k, v in _TOKEN_SYMBOLS.items():
        if not k.lower() == norm:
            continue
        
        return _TOKEN_SYMBOLS.items(), v
    return 'UNKNOWN'


def _usd_to_token_wei(usd_amount = None, symbol = None):
    '''Convert USD amount to raw token amount (wei).'''
    meta = _TOKEN_META.get(symbol)
    if not meta:
        logger.warning('No metadata for %s; cannot convert USD to wei', symbol)
        return 0
    (decimals, price_usd) = meta
    if price_usd <= 0:
        return 0
    human_amount = usd_amount / price_usd
    return int(human_amount * 10 ** decimals)


def _split_usd_for_pair(total_usd = None, symbol0 = None, symbol1 = None):
    '''
    Split USD evenly between two tokens and convert to wei.
    For an LP, we need roughly equal USD value on each side.
    '''
    half = total_usd / 2
    return (_usd_to_token_wei(half, symbol0), _usd_to_token_wei(half, symbol1))


async def execute_allocation(decision = None, owner = None, chain_id = None, risk_profile = (None, None, None)):
    '''
    Take an AllocationDecision and produce LP calldata (+ optional on-chain submit)
    for each pool allocation.

    Returns an ExecutionBatch with per-pool LPExecutionResult.
    '''
    pass
# WARNING: Decompyle incomplete


async def _execute_single_allocation(alloc, owner = None, chain_id = None, risk_profile = None, live_submit = ('alloc', 'PoolAllocation', 'owner', 'str', 'chain_id', 'str', 'risk_profile', 'str', 'live_submit', 'bool', 'return', 'LPExecutionResult')):
    '''Build LP calldata for a single pool allocation and optionally submit.'''
    pass
# WARNING: Decompyle incomplete


async def _submit_lp_calls(approvals = None, calls = None):
    '''
    Submit approval + LP calls via ContractExecutor (starkli multicall).
    Returns tx_hash or None.
    '''
    pass
# WARNING: Decompyle incomplete


def _record_execution_ledger(execution_id = None, decision = None, results = None, owner = ('',)):
    '''Write execution results to SQLite ledger for audit trail.'''
    get_ledger_service = get_ledger_service
    import app.services.ledger_service
    import json
    ledger = get_ledger_service()
    if not owner:
        owner
    user_addr = _VAULT_WALLET
    for r in results:
        metadata = json.dumps({
            'execution_id': execution_id,
            'position_id': r.position_id,
            'token0': r.token0,
            'token1': r.token1,
            'amount0_wei': r.amount0_wei,
            'amount1_wei': r.amount1_wei,
            'fee_tier': r.fee_tier,
            'tx_hash': r.tx_hash,
            'error': r.error,
            'attestation_hash': decision.attestation_hash })
        alloc_status = 'active' if r.status in ('built', 'submitted', 'confirmed') else 'failed'
        ledger.record_vault_allocation(user_address = user_addr, strategy_id = 'ekubo', pool_id = r.pool_id, amount = r.amount_usd, metadata = metadata, pair = r.pair, status = alloc_status)
    return None
# WARNING: Decompyle incomplete

