[package]
name = "ezkl_kzg_verifier"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v1.0.1" }
garaga_verifier_noir_ezkl_bridge = { path = "../garaga_verifier_noir_ezkl_bridge" }

[cairo]
sierra-replace-ids = false
inlining-strategy = "default"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
