"""
Proof Registry Service — local proof storage + Starknet on-chain submission.

Tracks every EZKL proof generated by the system with metadata,
verification status, and optional on-chain submission to the
ValidationProofRegistry contract on Starknet Sepolia.

Storage: SQLite (proof_registry.db) in the data directory.
On-chain: ValidationProofRegistry at VALIDATION_PROOF_REGISTRY_ADDRESS.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import sqlite3
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

DB_PATH = Path(__file__).resolve().parent.parent / "data" / "proof_registry.db"
DB_PATH.parent.mkdir(parents=True, exist_ok=True)

# Starknet config from environment
REGISTRY_ADDRESS = os.getenv(
    "VALIDATION_PROOF_REGISTRY_ADDRESS",
    "0x20ea9a32eae3fe6fe5137ca9f576383f8723913e1619f17120cf1aeb7e06305",
)
EXECUTOR_RPC = os.getenv("EXECUTOR_RPC_URL", "https://api.cartridge.gg/x/starknet/sepolia")
EXECUTOR_PK = os.getenv("EXECUTOR_PRIVATE_KEY", "")
ACCOUNT_PATH = os.getenv("EXECUTOR_ACCOUNT_PATH", "/root/.starkli-wallets/deployer/account.json")

# Default agent_id for proofs (short-string felt for "zkdefi")
AGENT_ID = int.from_bytes(b"zkdefi", "big")


# ── Data model ──────────────────────────────────────────────────────────

@dataclass
class ProofRecord:
    """Local proof record."""
    id: int
    proof_hash: str            # SHA-256 hex of proof bytes (primary key for lookups)
    model_name: str            # e.g. "creditworthiness", "yield_forecast", "anomaly_detector"
    user_address: str          # Starknet address of user the proof is about
    proof_type: str            # "groth16" or "ezkl_kzg"
    action_type: str           # "credit_check", "yield_estimate", "anomaly_scan"
    proof_size_bytes: int
    inference_output: str      # JSON array of output values
    verified_locally: bool     # Whether we verified before storing
    created_at: float          # Unix timestamp
    metadata_json: str = "{}"  # JSON object with bridge/runtime metadata
    # On-chain fields
    tx_hash: str | None = None       # Starknet tx hash if submitted
    on_chain_proof_id: int | None = None
    submitted_at: float | None = None

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        try:
            d["metadata"] = json.loads(self.metadata_json or "{}")
        except Exception:
            d["metadata"] = {}
        d["created_at_iso"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(d["created_at"]))
        if d["submitted_at"]:
            d["submitted_at_iso"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(d["submitted_at"]))
        return d


# ── SQL schema ──────────────────────────────────────────────────────────

_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS proofs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    proof_hash      TEXT UNIQUE NOT NULL,
    model_name      TEXT NOT NULL,
    user_address    TEXT NOT NULL DEFAULT '',
    proof_type      TEXT NOT NULL DEFAULT 'ezkl_kzg',
    action_type     TEXT NOT NULL DEFAULT '',
    proof_size_bytes INTEGER NOT NULL DEFAULT 0,
    inference_output TEXT NOT NULL DEFAULT '[]',
    verified_locally INTEGER NOT NULL DEFAULT 0,
    created_at      REAL NOT NULL,
    metadata_json   TEXT NOT NULL DEFAULT '{}',
    tx_hash         TEXT,
    on_chain_proof_id INTEGER,
    submitted_at    REAL
);
CREATE INDEX IF NOT EXISTS idx_proofs_model ON proofs(model_name);
CREATE INDEX IF NOT EXISTS idx_proofs_user  ON proofs(user_address);
CREATE INDEX IF NOT EXISTS idx_proofs_hash  ON proofs(proof_hash);
"""


# ── Service ─────────────────────────────────────────────────────────────

class ProofRegistryService:
    """
    Local proof registry with optional Starknet on-chain submission.

    Usage:
        svc = get_proof_registry()
        record = svc.store_proof(proof_hash="0xabc...", model_name="creditworthiness", ...)
        all_proofs = svc.list_proofs(model_name="yield_forecast")
        tx = await svc.submit_on_chain(proof_hash)
    """

    def __init__(self) -> None:
        self._db_path = str(DB_PATH)
        self._init_db()
        self._starknet_available = False
        self._account = None
        self._contract = None
        logger.info("ProofRegistryService initialized (db=%s)", self._db_path)

    def _init_db(self) -> None:
        conn = sqlite3.connect(self._db_path)
        conn.executescript(_CREATE_TABLE)
        columns = {row[1] for row in conn.execute("PRAGMA table_info(proofs)").fetchall()}
        if "metadata_json" not in columns:
            conn.execute("ALTER TABLE proofs ADD COLUMN metadata_json TEXT NOT NULL DEFAULT '{}'")
        conn.close()

    def _conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self._db_path)
        conn.row_factory = sqlite3.Row
        return conn

    # ── Store a proof ───────────────────────────────────────────────────

    def store_proof(
        self,
        proof_hash: str,
        model_name: str,
        user_address: str = "",
        proof_type: str = "ezkl_kzg",
        action_type: str = "",
        proof_size_bytes: int = 0,
        inference_output: list[float] | None = None,
        verified_locally: bool = False,
        metadata: dict[str, Any] | None = None,
    ) -> ProofRecord:
        """Store a proof record. Returns existing if proof_hash already stored."""
        now = time.time()
        output_json = json.dumps(inference_output or [])
        metadata_json = json.dumps(metadata or {}, sort_keys=True)

        conn = self._conn()
        try:
            # Check if already stored
            row = conn.execute(
                "SELECT * FROM proofs WHERE proof_hash = ?", (proof_hash,)
            ).fetchone()
            if row:
                return self._row_to_record(row)

            conn.execute(
                """INSERT INTO proofs
                   (proof_hash, model_name, user_address, proof_type, action_type,
                    proof_size_bytes, inference_output, verified_locally, created_at, metadata_json)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (proof_hash, model_name, user_address, proof_type, action_type,
                 proof_size_bytes, output_json, int(verified_locally), now, metadata_json),
            )
            conn.commit()
            row = conn.execute(
                "SELECT * FROM proofs WHERE proof_hash = ?", (proof_hash,)
            ).fetchone()
            record = self._row_to_record(row)
            logger.info(
                "Stored proof: hash=%s model=%s user=%s",
                proof_hash[:16], model_name, user_address[:16] if user_address else "-",
            )
            return record
        finally:
            conn.close()

    # ── Query proofs ────────────────────────────────────────────────────

    def get_proof(self, proof_hash: str) -> ProofRecord | None:
        conn = self._conn()
        try:
            row = conn.execute(
                "SELECT * FROM proofs WHERE proof_hash = ?", (proof_hash,)
            ).fetchone()
            return self._row_to_record(row) if row else None
        finally:
            conn.close()

    def list_proofs(
        self,
        model_name: str | None = None,
        user_address: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[ProofRecord]:
        """List proofs with optional filters."""
        clauses: list[str] = []
        params: list[Any] = []
        if model_name:
            clauses.append("model_name = ?")
            params.append(model_name)
        if user_address:
            clauses.append("user_address = ?")
            params.append(user_address)

        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        sql = f"SELECT * FROM proofs {where} ORDER BY created_at DESC LIMIT ? OFFSET ?"
        params.extend([limit, offset])

        conn = self._conn()
        try:
            rows = conn.execute(sql, params).fetchall()
            return [self._row_to_record(r) for r in rows]
        finally:
            conn.close()

    def get_stats(self) -> dict[str, Any]:
        """Aggregate statistics."""
        conn = self._conn()
        try:
            total = conn.execute("SELECT COUNT(*) FROM proofs").fetchone()[0]
            verified = conn.execute(
                "SELECT COUNT(*) FROM proofs WHERE verified_locally = 1"
            ).fetchone()[0]
            on_chain = conn.execute(
                "SELECT COUNT(*) FROM proofs WHERE tx_hash IS NOT NULL"
            ).fetchone()[0]
            by_model = {}
            for row in conn.execute(
                "SELECT model_name, COUNT(*) as cnt FROM proofs GROUP BY model_name"
            ).fetchall():
                by_model[row["model_name"]] = row["cnt"]
            return {
                "total_proofs": total,
                "verified_locally": verified,
                "submitted_on_chain": on_chain,
                "by_model": by_model,
            }
        finally:
            conn.close()

    # ── On-chain submission ─────────────────────────────────────────────

    async def _ensure_starknet(self) -> bool:
        """Lazy-init Starknet account + contract proxy."""
        if self._starknet_available:
            return True
        if not EXECUTOR_PK:
            logger.warning("No EXECUTOR_PRIVATE_KEY — on-chain submission disabled")
            return False
        try:
            from starknet_py.net.full_node_client import FullNodeClient
            from starknet_py.net.account.account import Account
            from starknet_py.net.models import StarknetChainId
            from starknet_py.net.signer.stark_curve_signer import KeyPair

            # Derive address from account file
            account_addr = self._load_account_address()
            if not account_addr:
                logger.warning("Cannot resolve deployer address — on-chain submission disabled")
                return False

            client = FullNodeClient(node_url=EXECUTOR_RPC)
            pk_int = int(EXECUTOR_PK, 16) if EXECUTOR_PK.startswith("0x") else int(EXECUTOR_PK)
            self._account = Account(
                address=int(account_addr, 16),
                client=client,
                key_pair=KeyPair.from_private_key(pk_int),
                chain=StarknetChainId.SEPOLIA,
            )
            self._account._cairo_version = 1
            self._starknet_available = True
            logger.info("Starknet account connected for proof submission")
            return True
        except Exception as e:
            logger.warning("Starknet init failed: %s", e)
            return False

    def _load_account_address(self) -> str | None:
        """Load account address from starkli wallet JSON."""
        try:
            with open(ACCOUNT_PATH) as f:
                data = json.load(f)
            return data.get("deployment", {}).get("address")
        except Exception:
            return None

    async def submit_on_chain(self, proof_hash: str) -> dict[str, Any]:
        """
        Submit a proof to the ValidationProofRegistry on Starknet.

        Returns {"success": bool, "tx_hash": str | None, "error": str | None}
        """
        record = self.get_proof(proof_hash)
        if not record:
            return {"success": False, "tx_hash": None, "error": "Proof not found in local registry"}
        if record.tx_hash:
            return {"success": True, "tx_hash": record.tx_hash, "error": None, "already_submitted": True}

        if not await self._ensure_starknet():
            return {"success": False, "tx_hash": None, "error": "Starknet not available"}

        try:
            from starknet_py.hash.selector import get_selector_from_name
            from starknet_py.net.client_models import Call, ResourceBoundsMapping

            # Convert proof_hash to felt252 (truncate to 31 bytes for Starknet)
            hash_bytes = bytes.fromhex(proof_hash.replace("0x", ""))[:31]
            fact_hash = int.from_bytes(hash_bytes, "big")

            # Map model_name to proof_type and action_type felt252
            proof_type_felt = int.from_bytes(b"ezkl_kzg", "big")
            action_map = {
                "creditworthiness": b"credit_check",
                "yield_forecast": b"yield_estimate",
                "anomaly_detector": b"anomaly_scan",
            }
            action_bytes = action_map.get(record.model_name, record.model_name.encode()[:31])
            action_type_felt = int.from_bytes(action_bytes, "big")

            call = Call(
                to_addr=int(REGISTRY_ADDRESS, 16),
                selector=get_selector_from_name("register_proof"),
                calldata=[
                    fact_hash,                  # fact_hash
                    AGENT_ID,                   # agent_id
                    proof_type_felt,            # proof_type
                    action_type_felt,           # action_type
                    0,                          # verifier_address (placeholder)
                ],
            )

            nonce = await self._account.get_nonce(block_number="latest")
            draft = await self._account._prepare_invoke_v3(
                [call],
                resource_bounds=ResourceBoundsMapping.init_with_zeros(),
                nonce=nonce,
            )
            estimated = await self._account.estimate_fee(draft, block_number="latest")
            rbm = estimated.to_resource_bounds()
            resp = await self._account.execute_v3(calls=[call], resource_bounds=rbm, nonce=nonce)
            await self._account.client.wait_for_tx(resp.transaction_hash)
            tx_hash = hex(resp.transaction_hash)

            # Update local record
            conn = self._conn()
            try:
                conn.execute(
                    "UPDATE proofs SET tx_hash = ?, submitted_at = ? WHERE proof_hash = ?",
                    (tx_hash, time.time(), proof_hash),
                )
                conn.commit()
            finally:
                conn.close()

            logger.info("Proof %s submitted on-chain: tx=%s", proof_hash[:16], tx_hash)
            return {"success": True, "tx_hash": tx_hash, "error": None}

        except Exception as e:
            logger.error("On-chain submission failed for %s: %s", proof_hash[:16], e)
            return {"success": False, "tx_hash": None, "error": str(e)}

    # ── Helpers ─────────────────────────────────────────────────────────

    @staticmethod
    def _row_to_record(row: sqlite3.Row) -> ProofRecord:
        return ProofRecord(
            id=row["id"],
            proof_hash=row["proof_hash"],
            model_name=row["model_name"],
            user_address=row["user_address"],
            proof_type=row["proof_type"],
            action_type=row["action_type"],
            proof_size_bytes=row["proof_size_bytes"],
            inference_output=row["inference_output"],
            verified_locally=bool(row["verified_locally"]),
            created_at=row["created_at"],
            metadata_json=row["metadata_json"] or "{}",
            tx_hash=row["tx_hash"],
            on_chain_proof_id=row["on_chain_proof_id"],
            submitted_at=row["submitted_at"],
        )


# ── Singleton ────────────────────────────────────────────────────────────

_instance: ProofRegistryService | None = None


def get_proof_registry() -> ProofRegistryService:
    """Get or create the proof registry singleton."""
    global _instance
    if _instance is None:
        _instance = ProofRegistryService()
    return _instance
