"""
Vault Allocation Executor — Phase C

Takes an AllocationDecision (from ai_allocation.py) and:
1. Parses pool_ids → token0 / token1 addresses
2. Converts USD amounts → token-wei amounts using static price table
3. Calls ekubo_lp_service.build_lp_add() for each pool allocation
4. Optionally submits on-chain when EXECUTOR_LIVE_SUBMIT=true
5. Records execution results in the SQLite ledger (pending → active / failed)
6. Returns structured ExecutionResult per allocation

No mocks.  Depends on:
  - ekubo_execution_service.build_lp_add_calldata (tick auto-estimation)
  - contract_executor.ContractExecutor (starkli invoke)
  - real_pool_aggregator._TOKEN_META (price / decimals)
  - ledger_service.LedgerService (audit trail)
"""

from __future__ import annotations

import logging
import os
import uuid
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from typing import Any

from app.services.ai_allocation import AllocationDecision, PoolAllocation
from app.services.real_pool_aggregator import _TOKEN_META, _TOKEN_SYMBOLS

logger = logging.getLogger(__name__)

# ── Constants ───────────────────────────────────────────────────────────

_DEFAULT_FEE_TIER = 3000                         # 0.3 %
_CHAIN_ID = os.getenv("EKUBO_CHAIN_ID", "0x534e5f5345504f4c4941")  # Sepolia
_VAULT_WALLET = os.getenv(
    "VAULT_WALLET_ADDRESS",
    "0x05fe812551bec726f1bf5026d5fb88f06ed411a753fb4468f9e19ebf8ced1b3d",
)


# ── Data structures ─────────────────────────────────────────────────────

@dataclass
class LPExecutionResult:
    """Result for one LP position build/submit."""
    pool_id: str
    pair: str
    position_id: str | None
    token0: str
    token1: str
    amount0_wei: int
    amount1_wei: int
    amount_usd: float
    fee_tier: int
    status: str                     # built | submitted | confirmed | failed
    tx_hash: str | None
    error: str | None
    warnings: list[str]
    calldata: dict[str, Any] | None  # {contract_address, entrypoint, calldata} for client signing

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ExecutionBatch:
    """Full batch result for an allocation execution."""
    execution_id: str
    attestation_hash: str
    risk_profile: str
    deposit_amount: float
    results: list[LPExecutionResult]
    reserve_usd: float
    live_submitted: bool
    timestamp: str

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["results"] = [r.to_dict() for r in self.results]
        return d


# ── Helpers: pool_id → token addresses ──────────────────────────────────

# Reverse lookup: symbol → longest Starknet-native address (0x0…)
_SYMBOL_TO_ADDRESS: dict[str, str] = {}
for _addr, _sym in _TOKEN_SYMBOLS.items():
    # Prefer Starknet mainnet-length addresses (66 chars with 0x)
    if _sym not in _SYMBOL_TO_ADDRESS or len(_addr) > len(_SYMBOL_TO_ADDRESS.get(_sym, "")):
        _SYMBOL_TO_ADDRESS[_sym] = _addr


def _parse_pool_id(pool_id: str) -> tuple[str, str, int]:
    """
    Parse pool_id generated by real_pool_aggregator._pool_id().
    Format: ekubo:{token0_addr}:{token1_addr}:{fee}:{idx}
    Returns (token0, token1, fee_tier).
    """
    parts = pool_id.split(":")
    if len(parts) >= 4 and parts[0] == "ekubo":
        token0_raw = parts[1]
        token1_raw = parts[2]
        fee_raw = parts[3]
        try:
            fee_tier = int(float(fee_raw) * 1_000_000) if "." in fee_raw else int(fee_raw)
        except (ValueError, TypeError):
            fee_tier = _DEFAULT_FEE_TIER
        return token0_raw, token1_raw, fee_tier

    # Fallback: try to extract from pair symbol in the allocation
    return "", "", _DEFAULT_FEE_TIER


def _resolve_token_address(raw: str) -> str:
    """If raw is already a hex address, return it. Otherwise try symbol lookup."""
    if raw.startswith("0x") and len(raw) > 6:
        return raw
    # Handle "0x0" → ETH
    if raw == "0x0" or raw == "0x00":
        return _SYMBOL_TO_ADDRESS.get("ETH", raw)
    # Maybe it's a symbol
    return _SYMBOL_TO_ADDRESS.get(raw.upper(), raw)


def _symbol_for_address(addr: str) -> str:
    """Resolve address → symbol for price/decimal lookup."""
    norm = addr.strip().lower()
    for k, v in _TOKEN_SYMBOLS.items():
        if k.lower() == norm:
            return v
    return "UNKNOWN"


def _usd_to_token_wei(usd_amount: float, symbol: str) -> int:
    """Convert USD amount to raw token amount (wei)."""
    meta = _TOKEN_META.get(symbol)
    if not meta:
        logger.warning("No metadata for %s; cannot convert USD to wei", symbol)
        return 0
    decimals, price_usd = meta
    if price_usd <= 0:
        return 0
    human_amount = usd_amount / price_usd
    return int(human_amount * (10 ** decimals))


def _split_usd_for_pair(
    total_usd: float,
    symbol0: str,
    symbol1: str,
) -> tuple[int, int]:
    """
    Split USD evenly between two tokens and convert to wei.
    For an LP, we need roughly equal USD value on each side.
    """
    half = total_usd / 2.0
    return _usd_to_token_wei(half, symbol0), _usd_to_token_wei(half, symbol1)


# ── Core executor ───────────────────────────────────────────────────────

async def execute_allocation(
    decision: AllocationDecision,
    owner: str | None = None,
    chain_id: str | None = None,
    risk_profile: str | None = None,
) -> ExecutionBatch:
    """
    Take an AllocationDecision and produce LP calldata (+ optional on-chain submit)
    for each pool allocation.

    Returns an ExecutionBatch with per-pool LPExecutionResult.
    """
    from app.services.ekubo_execution_service import build_lp_add_calldata

    owner = owner or _VAULT_WALLET
    chain_id = chain_id or _CHAIN_ID
    risk_profile = risk_profile or decision.risk_profile
    live_submit = os.getenv("EXECUTOR_LIVE_SUBMIT", "false").lower() == "true"

    execution_id = f"exec_{uuid.uuid4().hex[:12]}"
    results: list[LPExecutionResult] = []

    for alloc in decision.allocations:
        result = await _execute_single_allocation(
            alloc=alloc,
            owner=owner,
            chain_id=chain_id,
            risk_profile=risk_profile,
            live_submit=live_submit,
        )
        results.append(result)

    # Record in ledger
    _record_execution_ledger(
        execution_id=execution_id,
        decision=decision,
        results=results,
        owner=owner,
    )

    return ExecutionBatch(
        execution_id=execution_id,
        attestation_hash=decision.attestation_hash,
        risk_profile=decision.risk_profile,
        deposit_amount=decision.deposit_amount,
        results=results,
        reserve_usd=decision.reserve_usd,
        live_submitted=live_submit,
        timestamp=datetime.now(timezone.utc).isoformat(),
    )


async def _execute_single_allocation(
    alloc: PoolAllocation,
    owner: str,
    chain_id: str,
    risk_profile: str,
    live_submit: bool,
) -> LPExecutionResult:
    """Build LP calldata for a single pool allocation and optionally submit."""
    from app.services.ekubo_execution_service import build_lp_add_calldata

    token0_raw, token1_raw, fee_tier = _parse_pool_id(alloc.pool_id)
    token0 = _resolve_token_address(token0_raw)
    token1 = _resolve_token_address(token1_raw)

    sym0 = _symbol_for_address(token0)
    sym1 = _symbol_for_address(token1)

    # Fallback: if pool_id didn't parse well, try to extract from pair name
    if not token0 or not token0.startswith("0x") or len(token0) < 6:
        pair_parts = alloc.pair.split("/")
        if len(pair_parts) == 2:
            sym0 = pair_parts[0].strip()
            sym1 = pair_parts[1].strip()
            token0 = _SYMBOL_TO_ADDRESS.get(sym0, "")
            token1 = _SYMBOL_TO_ADDRESS.get(sym1, "")

    if not token0 or not token1:
        return LPExecutionResult(
            pool_id=alloc.pool_id,
            pair=alloc.pair,
            position_id=None,
            token0=token0,
            token1=token1,
            amount0_wei=0,
            amount1_wei=0,
            amount_usd=alloc.amount_usd,
            fee_tier=fee_tier,
            status="failed",
            tx_hash=None,
            error=f"Cannot resolve token addresses for {alloc.pair}",
            warnings=[],
            calldata=None,
        )

    amount0, amount1 = _split_usd_for_pair(alloc.amount_usd, sym0, sym1)

    if amount0 <= 0 or amount1 <= 0:
        return LPExecutionResult(
            pool_id=alloc.pool_id,
            pair=alloc.pair,
            position_id=None,
            token0=token0,
            token1=token1,
            amount0_wei=amount0,
            amount1_wei=amount1,
            amount_usd=alloc.amount_usd,
            fee_tier=fee_tier,
            status="failed",
            tx_hash=None,
            error=f"Zero amount after USD conversion for {sym0}/{sym1}",
            warnings=[],
            calldata=None,
        )

    try:
        lp_result = await build_lp_add_calldata(
            chain_id=chain_id,
            owner=owner,
            token0=token0,
            token1=token1,
            amount0_wei=amount0,
            amount1_wei=amount1,
            fee_tier=fee_tier,
            lower_tick=None,        # auto-estimated by preview
            upper_tick=None,
            risk_profile=risk_profile,
        )
    except Exception as e:
        logger.error("build_lp_add_calldata failed for %s: %s", alloc.pair, e)
        return LPExecutionResult(
            pool_id=alloc.pool_id,
            pair=alloc.pair,
            position_id=None,
            token0=token0,
            token1=token1,
            amount0_wei=amount0,
            amount1_wei=amount1,
            amount_usd=alloc.amount_usd,
            fee_tier=fee_tier,
            status="failed",
            tx_hash=None,
            error=str(e),
            warnings=[],
            calldata=None,
        )

    position_id = lp_result.get("position_id")
    warnings = lp_result.get("warnings", [])
    calls = lp_result.get("calls", [])
    approvals = lp_result.get("approvals", [])

    # Build combined calldata for client signing
    combined_calldata: dict[str, Any] | None = None
    if calls:
        combined_calldata = {
            "approvals": approvals,
            "calls": calls,
        }

    status = "built"
    tx_hash: str | None = None

    # Live submit if enabled
    if live_submit and calls:
        tx_hash = await _submit_lp_calls(approvals, calls)
        if tx_hash:
            status = "submitted"
            logger.info(
                "LP position %s submitted on-chain: %s (pair=%s)",
                position_id, tx_hash, alloc.pair,
            )
        else:
            # Calldata is still valid for client to sign manually
            status = "built"
            warnings.append("Live submit attempted but failed; calldata available for manual signing.")

    return LPExecutionResult(
        pool_id=alloc.pool_id,
        pair=alloc.pair,
        position_id=position_id,
        token0=token0,
        token1=token1,
        amount0_wei=amount0,
        amount1_wei=amount1,
        amount_usd=alloc.amount_usd,
        fee_tier=fee_tier,
        status=status,
        tx_hash=tx_hash,
        error=None,
        warnings=warnings,
        calldata=combined_calldata,
    )


async def _submit_lp_calls(
    approvals: list[dict[str, Any]],
    calls: list[dict[str, Any]],
) -> str | None:
    """
    Submit approval + LP calls via ContractExecutor (starkli multicall).
    Returns tx_hash or None.
    """
    try:
        from app.services.contract_executor import ContractExecutor
        executor = ContractExecutor()
        if not executor.can_submit_live():
            return None

        # Submit approvals first
        for approval in approvals:
            token = approval.get("token", "")
            spender = approval.get("spender", "")
            amount = approval.get("amount", "0")
            if int(amount) <= 0:
                continue
            # ERC20 approve(spender, amount_low, amount_high)
            amount_int = int(amount)
            amount_low = amount_int & ((1 << 128) - 1)
            amount_high = amount_int >> 128
            result = await executor._invoke(
                token,
                "approve",
                [spender, str(amount_low), str(amount_high)],
            )
            if not result:
                logger.warning("Approval tx failed for %s → %s", token, spender)
                return None

        # Submit LP call
        for call in calls:
            contract = call.get("contract_address", "")
            entrypoint = call.get("entrypoint", "")
            calldata = call.get("calldata", [])
            result = await executor._invoke(contract, entrypoint, calldata)
            if result:
                return result

        return None
    except Exception as e:
        logger.warning("_submit_lp_calls error: %s", e)
        return None


# ── Ledger recording ────────────────────────────────────────────────────

def _record_execution_ledger(
    execution_id: str,
    decision: AllocationDecision,
    results: list[LPExecutionResult],
    owner: str = "",
) -> None:
    """Write execution results to SQLite ledger for audit trail."""
    try:
        from app.services.ledger_service import get_ledger_service
        import json

        ledger = get_ledger_service()
        user_addr = owner or _VAULT_WALLET
        for r in results:
            metadata = json.dumps({
                "execution_id": execution_id,
                "position_id": r.position_id,
                "token0": r.token0,
                "token1": r.token1,
                "amount0_wei": r.amount0_wei,
                "amount1_wei": r.amount1_wei,
                "fee_tier": r.fee_tier,
                "tx_hash": r.tx_hash,
                "error": r.error,
                "attestation_hash": decision.attestation_hash,
            })
            # Determine status from execution result
            alloc_status = "active" if r.status in ("built", "submitted", "confirmed") else "failed"
            ledger.record_vault_allocation(
                user_address=user_addr,
                strategy_id=f"ekubo",
                pool_id=r.pool_id,
                amount=r.amount_usd,
                metadata=metadata,
                pair=r.pair,
                status=alloc_status,
            )
    except Exception as e:
        logger.warning("Ledger recording failed (non-fatal): %s", e)
