[package]
name = "receipt_registry_v01"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"

[dev-dependencies]
snforge_std = "0.50.0"
cairo_test = "2.14.0"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs = true
allowed-libfuncs-deny = false
